on:
  push:
    branches:
      - main

jobs:
  build:
    container:
      image: rustlang/rust:nightly
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | bash - \
                && apt-get install -y nodejs
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          cargo build
          cd glsl2hlsl-wasm
          wasm-pack build
          cd www
          npm install
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: website
          path: |
            glsl2hlsl-wasm/www/dist/
